export const constantText = {
  YES: "Yes",
  NO: "No",
  STRING: "String",
  NUMBER: "Number",
  BOOLEAN: "Boolean",
  OBJECT: "Object",
  FUNCTION: "Function",
  DATE: "Date",
  REGEXP: "RegExp",
  ARRAY: "Array",
  NULL: "Null",
  UNDEFINED: "Undeﬁned",
  ERROR: "Error",
  CAPITALIZE: "capitalize",
  LOWERCASE: "lowercase",
  INVALID_TYPE: "Invalid type",
  NOT_A_STRING: "Not a string",
  ENTER_VALID_INPUT: "Enter valid input",
  ENTER_VALID_INPUTS: "Enter valid inputs",
  NAME_VALIDATION_MESSAGE: "Name must be of minimum length 8 characters",
  EMAIL_VALIDATION_MESSAGE: "Enter valid email",
  PASSWORD_VALIDATION_MESSAGE: "Password must contain one digit from 1 to 9, one lowercase letter, one uppercase letter, one special character, no space, and it must be 8-16 characters long",
};
