export const constantText = {
  YES: "Yes",
  NO: "No",
  STRING: "String",
  NUMBER: "Number",
  BOOLEAN: "Boolean",
  OBJECT: "Object",
  FUNCTION: "Function",
  DATE: "Date",
  REGEXP: "RegExp",
  ARRAY: "Array",
  NULL: "Null",
  UNDEFINED: "Undeﬁned",
  ERROR: "Error",
  CAPITALIZE: "capitalize",
  LOWERCASE: "lowercase",
  INVALID_TYPE: "Invalid type",
  NOT_A_STRING: "Not a string",
};
